version: 2

models:
  - name: stg_clientes
    description: >
      Modelo de staging para clientes. Contém os dados brutos da fonte,
      com renomeações básicas de colunas e conversões de tipos de dados.
    columns:
      - name: cliente_id
        description: Identificador único do cliente
        tests:
          - unique
          - not_null
      - name: nome
        description: Nome completo do cliente
        tests:
          - not_null
      - name: email
        description: Email de contato do cliente
        tests:
          - not_null
          - unique
      - name: data_cadastro
        description: Data e hora de cadastro do cliente
      - name: ultima_atualizacao
        description: Data e hora da última atualização dos dados do cliente
      - name: data_ingestao_airbyte
        description: Data e hora em que o registro foi ingerido pelo Airbyte

  - name: stg_pedidos
    description: >
      Modelo de staging para pedidos. Contém os dados brutos da fonte,
      com renomeações básicas de colunas e conversões de tipos de dados.
    columns:
      - name: pedido_id
        description: Identificador único do pedido
        tests:
          - unique
          - not_null
      - name: cliente_id
        description: Identificador do cliente que fez o pedido
        tests:
          - not_null
          - relationships:
              to: ref('stg_clientes')
              field: cliente_id
      - name: produto
        description: Nome do produto adquirido
        tests:
          - not_null
      - name: quantidade
        description: Quantidade do produto adquirida
        tests:
          - not_null
      - name: preco_unitario
        description: Preço unitário do produto no momento do pedido
        tests:
          - not_null
      - name: data_pedido
        description: Data e hora em que o pedido foi registrado
      - name: ultima_atualizacao
        description: Data e hora da última atualização dos dados do pedido
      - name: data_ingestao_airbyte
        description: Data e hora em que o registro foi ingerido pelo Airbyte
