# dbt_profiles/profiles.yml

default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_DB_HOST', 'postgres_source_db') }}"  # Uso de variáveis de ambiente
      user: "{{ env_var('DBT_DB_USER', 'user_source') }}"
      password: "{{ env_var('DBT_DB_PASSWORD', 'password_source') }}"
      port: "{{ env_var('DBT_DB_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_DB_NAME', 'db_source') }}"
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10

    # Configuração para ambiente de produção
    prod:
      type: postgres
      host: "{{ env_var('DBT_PROD_HOST') }}"
      user: "{{ env_var('DBT_PROD_USER') }}"
      password: "{{ env_var('DBT_PROD_PASSWORD') }}"
      port: "{{ env_var('DBT_PROD_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('DBT_PROD_DBNAME') }}"
      schema: public
      threads: 8
      keepalives_idle: 0
      connect_timeout: 10